<?php

const STATUS_INACTIVE = 0;
const STATUS_ACTIVE = 1;


const MEMBER_TYPE_STUDENT = 1;
const MEMBER_TYPE_LECTURER = 2;
const MEMBER_TYPE_PROFESSOR = 3;
const MEMBER_TYPE_LIBRARIAN = 4;
const MEMBER_TYPE_SPECIAL = 5;
const MEMBER_TYPE_OTHERS = 6;
